services:
  neo4j:
    image: neo4j # pull neo4j image from docker-hub
    hostname: neo4j
    container_name: neo4j
    restart: unless-stopped
    volumes:
      - ./neo4j_data:/data
    ports:
      - 7474:7474 # http ui
      - 7687:7687 # bolt
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/changeme
    tmpfs:
      - /var/lib/neo4j/run
